---
functional:
  - Авторизованный пользователь должен иметь возможность создать новую игру 
  - При создании новой игры авторизованный пользователь должен иметь возможность выбрать уровень - elementary
  - При создании новой игры авторизованный пользователь должен иметь возможность выбрать уровень - easy
  - При создании новой игры авторизованный пользователь должен иметь возможность выбрать уровень – medium
  - При создании новой игры авторизованный пользователь должен иметь возможность выбрать уровень - hard
  - При создании новой игры авторизованный пользователь должен иметь возможность выбрать тип игры - с другим пользователем
  - При создании новой игры авторизованный пользователь должен иметь возможность выбрать тип игры - с другом
  - При создании новой игры авторизованный пользователь должен иметь возможность выбрать тип игры - с ботом
  - При создании новой игры авторизованный пользователь должен иметь возможность - выбрать задачу по названию
  - При создании новой игры авторизованный пользователь должен иметь возможность - выбрать задачу по тегу
  - При создании новой игры авторизованный пользователь должен иметь возможность - выбрать время на проведение игры (от 3 до 60 минут)
  - При создании игры авторизованным пользователем можно выбрать определенную игру, иначе она будет подобрана наугад
  - Незарегистрированный пользователь должен иметь возможность попробовать сыграть в простую игру с ботом
  - Пользователь должен иметь возможность открыть и посмотреть руководство для изучения игры
  - На странице игры пользователю доступно окно с поставленной задачей
  - Пользователь должен иметь возможность переключить задачу в игре на русский язык
  - Пользователь должен иметь возможность переключить задачу в игре на английский язык
  - На странице игры пользователь должен иметь возможность сдаться
  - На странице игры пользователь может менять язык программирования
  - На странице игры пользователю доступно окно редактора для ввода решения
  - Редактор для ввода кода должен выглядеть как проигрыватель
  - На странице игры пользователь должен иметь возможность сбросить код до исходного шаблона в окне для ввода 
  - На странице игры пользователь должен иметь возможность проверить своё решение
  - На странице игры пользователю доступно окно вывода результата (ошибки после проверки)
  - На странице игры пользователь может видеть редактор с кодом и вывод тестов другого игрока в режиме online 
  - На странице игры пользователь должен иметь возможность видеть чат и отправлять текст в чат
  - На странице игры пользователь должен иметь возможность устроить матчреванш
  - После игры должно высвечиваться сообщение о результате проверки игры (выигрыш или проигрыш)
  - На странице игры пользователь должен иметь возможность вернуться на главную страницу и с главной страницы вернуться обратно в игру
  - Другие пользователи могут следить за ходом игры в online режиме
  - Другие пользователи могут писать в чат игры
  - Пользователь должен иметь возможность принять приглашение в игру
  - Пользователь должен иметь возможность отказаться от приглашения в игру
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - На странице игры пользователь должен иметь возможность отправлять смайлики из редактора смайлов в чат
  - Пользователь должен иметь возможность зарегистрироваться на сайте с помощью email, страница регистрации должна содержать поля для ввода - nickname, email, password, password  confirmation
  - Все поля для регистрации через email обязательны для заполнения
  - При регистрации через email, ник должен содержать латинские буквы, цифры и символы подчеркивания
  - При регистрации через email, почта должна быть валидна
  - При регистрации через email, пароль должен состоять от 6 до 16 знаков
  - При регистрации через email, «пароль» и «подтверждения пароля» должны совпадать
  - Зарегистрированный пользователь должен иметь возможность авторизоваться через email
  - На сайте может авторизоваться только зарегистрированный пользователь
  - Если зарегистрированный через email пользователь забыл пароль от аккаунта при входе, то должен иметь возможность сбросить пароль  
  - Через один email может зарегистрироваться только один пользователь
  - При регистрации через email, никнейм должен быть уникальным
  - Пользователь должен иметь возможность войти на сайт с помощью аккаунта GitHub через страницу входа
  - Пользователь должен иметь возможность войти на сайт с помощью аккаунта GitHub через страницу регистрации
  - Пользователь должен иметь возможность войти на сайте с помощью аккаунта Discord через страницу входа
  - Пользователь должен иметь возможность войти на сайте с помощью аккаунта Discord через страницу регистрации
  - Авторизованный пользователь должен иметь возможность просматривать информацию своего профиля – ранг, рейтинг, количество сыгранных игр, активность
  - Авторизованный пользователь должен иметь возможность просматривать и редактировать параметры профиля – имя, язык программирования, клан
  - Авторизованный пользователь должен иметь возможность выйти из системы




