---
functional:
  - Пользователь должен иметь возможность решать задачи на скорость против другого игрока
  - На страницы игры пользователь может видеть редактор с кодом и вывод тестов другого игрока 
  - На странице игры пользователю доступно окно с поставленной задачей
  - На странице игры пользователю доступно окно редактора для ввода решения
  - На странице игры пользователь может менять язык программирования
  - На странице игры пользователь должен иметь возможность сдаться
  - На странице игры пользователь должен иметь возможность сбросить код до исходного шаблона в окне для ввода 
  - На странице игры пользователь должен иметь возможность проверить своё решение
  - На странице игры пользователю доступно окно вывода результата (ошибки после проверки)
  - На странице игры пользователь должен иметь возможность видеть чат и отправлять текст в чат
  - На странице игры пользователь должен иметь возможность устроить реванш
  - После игры должно высвечиваться сообщение о результате проверки игры (выигрыш или проигрышь)
  - На странице игры пользователь должен иметь возможность вернуться на главную страницу 
  - В игру можно играть с любым человеком, с ботом, с другом (игра должна быть доступна по ссылке)
  - Можно выбрать игру по уровню сложности 
  - При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Задачи даны на двух языках — русском и английском
  - Другие пользователи могут следить за ходом игры
  - Завершенная игра доступна в записи
  - Редактор для ввода кода выглядит как проигрыватель
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - Незарегистрированный пользователь должен иметь возможность попробовать сыграть в простую игру с ботом 
  - Авторизованный пользователь должен иметь возможность создать новую игру 
  - При создании новой игры пользователь должен иметь возможность - выбрать уровень (elementary, easy, medium, hard)
  - При создании новой игры пользователь должен иметь возможность – выбрать тип игры (с другим пользователем, с другом, с ботом)
  - При создании новой игры пользователь должен иметь возможность - выбрать время на проведение игры (от 3 до 45 минут)
  - При создании новой игры пользователь должен иметь возможность - выбрать задачу по названию или тегу
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь может посмотреть руководство по обучению игры 
  - Авторизованный пользователь должен иметь возможность просматривать страницу другого профиля 
  - Пользователь должен иметь возможность зарегистрироваться на сайте с помощью email, страница регистрации должна содержать поля для ввода - nickname, email, password, password  confirmation
  - При регистрации через email, ник должен содержать латинские буквы, цифры и символы подчеркивания
  - При регистрации через email, почта должна быть валидна
  - При регистрации через email, пароль должен состоять от 6 до 16 знаков
  - При регистрации через email, «пароль» и «подтверждения пароля» должны совпадать
  - Зарегистрированный пользователь должен иметь возможность авторизоваться через email
  - На сайте может авторизоваться только зарегистрированный пользователь
  - Если зарегистрированный через email пользователь забыл пароль от аккаунта при входе, то должен иметь возможность сбросить пароль  
  - Через один email может зарегистрироваться только один пользователь
  - При регистрации через email, никнейм должен быть уникальным
  - Пользователь должен иметь возможность войти на сайт с помощью аккаунта GitHub
  - Пользователь должен иметь возможность войти на сайте с помощью аккаунта Discord
  - Авторизованный пользователь должен иметь возможность просматривать информацию своего профиля – ранг, рейтинг, количество сыгранных игр, активность
  - Авторизованный пользователь должен иметь возможность просматривать и редактировать параметры профиля – имя, язык программирования.
  - Авторизованный пользователь должен иметь возможность редактировать звук игры в своём профиле
  - Авторизованный пользователь должен иметь возможность просматривать рейтинг всех пользователей за неделю, месяц и всё время
  - Авторизованный пользователь должен иметь возможность выйти из системы

